package org.usfirst.frc.team1701;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.HashMap;

import edu.wpi.first.wpilibj.networktables.NetworkTable;
import edu.wpi.first.wpilibj.vision.VisionPipeline;

import org.opencv.core.*;
import org.opencv.core.Core.*;
import org.opencv.features2d.FeatureDetector;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.*;
import org.opencv.objdetect.*;

/**
 * GripPipelin class.
 *
 * <p>
 * An OpenCV pipeline generated by GRIP.
 *
 * @author GRIP
 */
public class GripPipelin implements VisionPipeline {

	// Outputs
	private Mat blurOutput = new Mat();
	private Mat rgbThresholdOutput = new Mat();
	private ArrayList<MatOfPoint> findContoursOutput = new ArrayList<MatOfPoint>();
	private ArrayList<MatOfPoint> convexHullsOutput = new ArrayList<MatOfPoint>();
	private ArrayList<MatOfPoint> filterContoursOutput = new ArrayList<MatOfPoint>();
	private NetworkTable vision;

	static {
		System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
	}

	/**
	 * This is the primary method that runs the entire pipeline and updates the
	 * outputs.
	 */
	@Override
	public void process(Mat source0) {
		setupNetworktable();

		// Step Blur0:
		Mat blurInput = source0;
		BlurType blurType = BlurType.get("Gaussian Blur");
		double blurRadius = 1.8018018018018018;
		blur(blurInput, blurType, blurRadius, blurOutput);

		// Step RGB_Threshold0:
		Mat rgbThresholdInput = blurOutput;
		double[] rgbThresholdRed = { 165.10791366906474, 237.82828282828282 };
		double[] rgbThresholdGreen = { 243.07553956834533, 255.0 };
		double[] rgbThresholdBlue = { 236.19604316546764, 255.0 };
		rgbThreshold(rgbThresholdInput, rgbThresholdRed, rgbThresholdGreen, rgbThresholdBlue, rgbThresholdOutput);

		// Step Find_Contours0:
		Mat findContoursInput = rgbThresholdOutput;
		boolean findContoursExternalOnly = false;
		findContours(findContoursInput, findContoursExternalOnly, findContoursOutput);

		// Step Convex_Hulls0:
		ArrayList<MatOfPoint> convexHullsContours = findContoursOutput;
		convexHulls(convexHullsContours, convexHullsOutput);

		// Step Filter_Contours0:
		ArrayList<MatOfPoint> filterContoursContours = convexHullsOutput;
		double filterContoursMinArea = 65.0;
		double filterContoursMinPerimeter = 0.0;
		double filterContoursMinWidth = 0.0;
		double filterContoursMaxWidth = 125.0;
		double filterContoursMinHeight = 0.0;
		double filterContoursMaxHeight = 50.0;
		double[] filterContoursSolidity = { 100.0, 100.0 };
		double filterContoursMaxVertices = 30.0;
		double filterContoursMinVertices = 4.0;
		double filterContoursMinRatio = 0.0;
		double filterContoursMaxRatio = 10.0;
		filterContours(filterContoursContours, filterContoursMinArea, filterContoursMinPerimeter,
				filterContoursMinWidth, filterContoursMaxWidth, filterContoursMinHeight, filterContoursMaxHeight,
				filterContoursSolidity, filterContoursMaxVertices, filterContoursMinVertices, filterContoursMinRatio,
				filterContoursMaxRatio, filterContoursOutput);

		// end GRIP autogenerated
		List<MatOfPoint> possibleRect = new ArrayList<MatOfPoint>();
		List<MatOfPoint> possibleGoal = new ArrayList<MatOfPoint>();

		// put
		processContours(filterContoursOutput, possibleRect, possibleGoal);

		/*
		 * processing for rectangles (gear vision) ----- 
		 * loop 0 thru n-2 
		 * 		create boundingRect for i 
		 * 		test for proportion
		 * 		loop i+1 thru n-1 
		 * 			create boundingRect for second one 
		 * 			find widths of each 
		 * 			compare to find similar widths 
		 * 			find which is left/which is right 
		 * 			calculate distance between the right side of left rect and left side of right rect
		 * 			compare distance and width to desired ratio (6.25:2)
		 *			if there is a match, calculate score (how good a fit) 
		 *				set gearTargetFound = true 
		 *				if its a better score than previous match, record its data: centerX, centerY, score
		 */
		double bestCenterX = -1, bestCenterY = -1, score = 0;
		boolean gearTargetFound = false;

		for (int i = 0; i < possibleRect.size() - 1; i++) {
			Rect rect1 = Imgproc.boundingRect(possibleRect.get(i)); // creates a bounding rect around the first contour
			if (rect1.height <= 2.7 * rect1.width && >= 2.3*rect1.width){ // trying for 2.5:1 ratio, .4 tolerance
				for (int j = i + 1; j < possibleRect.size(); j++) { // compares the first to every contour past it
					Rect rect2 = Imgproc.boundingRect(possibleRect.get(j)); // bounding rect around the second contour
					double tolerance = .5;
					if(rect1.width >= .9 * rect2.width && rect1.width <= 1.1 * rect2.width){ // trying to get equal widths, .2 tolerance
						//can use the difference in widths to tell which side the robot is on
						double distance;
						double width = (rect1.width+rect2.width) / 2;
						if(rect1.x <= rect2.x){ // If Rect 1 is to the left
							distance = rect2.x - (rect1.x + rect1.width);
						} else{
							distance = rect1.x - (rect2.x + rect2.width);
						}
						if(distance*2 >= width*6.20 && distance*2 <= width*6.30){ // trying to get a 6.25:2 ratio, .1 tolerance
							gearTargetFound = true;
							double newScore = //------------------------------------
							if(newScore > score){ // ---------------------------------------------
								
							}//if(better score)
						}//if()
					} // if(widths)
				} // for(j)
			}//if(ratio)
		} // for(i)

		// write to network table
		try {
			vision.putBoolean("gearTargetFound", gearTargetFound);
			vision.putNumber("gearTargetX", 50);
			vision.putNumber("gearTargetY", 50);
			vision.putBoolean("goalTargetFound", true);
			vision.putNumber("goalTargetX", 50);
			vision.putNumber("goalTargetY", 50);
		} catch (Exception e) {
			;
		}
	}

	public void setupNetworktable() {
		try {
			NetworkTable.setClientMode();
			NetworkTable.setIPAddress("roboRIO-1701-FRC.local");
			vision = NetworkTable.getTable("vision");
		} catch (Exception e) {
			;
		}
	}

	public void processContours(ArrayList<MatOfPoint> contours, List<MatOfPoint> possibleRect,
			List<MatOfPoint> possibleGoal) {
		double precision = 0.007;
		for (MatOfPoint mOP : contours) {
			// approximate the shapes so that they have less
			// sides
			MatOfPoint2f approxCurve = new MatOfPoint2f();
			Imgproc.approxPolyDP(new MatOfPoint2f(mOP.toArray()), approxCurve,
					precision * Imgproc.arcLength(new MatOfPoint2f(mOP.toArray()), true), true);

			if (isRectangle(approxCurve)) {
				possibleRect.add(approxCurve);
			} else if (isGoal(approxCurve)) {
				possibleGoal.add(approxCurve);
			}
		} // for()

	}// MatOfPoint()

	public boolean isRectangle(MatOfPoint2f mOP) {
		if (Imgproc.contourArea(mOP) > 1000 && Imgproc.isContourConvex(new MatOfPoint(mOP.toArray()))
				&& mOP.toArray().length == 4) {
			return true;
		}
		return false;
	}

	public boolean isGoal(MatOfPoint2f mOP) {
		if (Imgproc.contourArea(mOP) > 1200 && Imgproc.isContourConvex(new MatOfPoint(mOP.toArray()))
				&& mOP.toArray().length >= 6 && mOP.toArray().length <= 20) {
			return true;
		}
		return false;
	}

	/**
	 * This method is a generated getter for the output of a Blur.
	 * 
	 * @return Mat output from Blur.
	 */
	public Mat blurOutput() {
		return blurOutput;
	}

	/**
	 * This method is a generated getter for the output of a RGB_Threshold.
	 * 
	 * @return Mat output from RGB_Threshold.
	 */
	public Mat rgbThresholdOutput() {
		return rgbThresholdOutput;
	}

	/**
	 * This method is a generated getter for the output of a Find_Contours.
	 * 
	 * @return ArrayList<MatOfPoint> output from Find_Contours.
	 */
	public ArrayList<MatOfPoint> findContoursOutput() {
		return findContoursOutput;
	}

	/**
	 * This method is a generated getter for the output of a Convex_Hulls.
	 * 
	 * @return ArrayList<MatOfPoint> output from Convex_Hulls.
	 */
	public ArrayList<MatOfPoint> convexHullsOutput() {
		return convexHullsOutput;
	}

	/**
	 * This method is a generated getter for the output of a Filter_Contours.
	 * 
	 * @return ArrayList<MatOfPoint> output from Filter_Contours.
	 */
	public ArrayList<MatOfPoint> filterContoursOutput() {
		return filterContoursOutput;
	}

	/**
	 * An indication of which type of filter to use for a blur. Choices are BOX,
	 * GAUSSIAN, MEDIAN, and BILATERAL
	 */
	enum BlurType {
		BOX("Box Blur"), GAUSSIAN("Gaussian Blur"), MEDIAN("Median Filter"), BILATERAL("Bilateral Filter");

		private final String label;

		BlurType(String label) {
			this.label = label;
		}

		public static BlurType get(String type) {
			if (BILATERAL.label.equals(type)) {
				return BILATERAL;
			} else if (GAUSSIAN.label.equals(type)) {
				return GAUSSIAN;
			} else if (MEDIAN.label.equals(type)) {
				return MEDIAN;
			} else {
				return BOX;
			}
		}

		@Override
		public String toString() {
			return this.label;
		}
	}

	/**
	 * Softens an image using one of several filters.
	 * 
	 * @param input
	 *            The image on which to perform the blur.
	 * @param type
	 *            The blurType to perform.
	 * @param doubleRadius
	 *            The radius for the blur.
	 * @param output
	 *            The image in which to store the output.
	 */
	private void blur(Mat input, BlurType type, double doubleRadius, Mat output) {
		int radius = (int) (doubleRadius + 0.5);
		int kernelSize;
		switch (type) {
		case BOX:
			kernelSize = 2 * radius + 1;
			Imgproc.blur(input, output, new Size(kernelSize, kernelSize));
			break;
		case GAUSSIAN:
			kernelSize = 6 * radius + 1;
			Imgproc.GaussianBlur(input, output, new Size(kernelSize, kernelSize), radius);
			break;
		case MEDIAN:
			kernelSize = 2 * radius + 1;
			Imgproc.medianBlur(input, output, kernelSize);
			break;
		case BILATERAL:
			Imgproc.bilateralFilter(input, output, -1, radius, radius);
			break;
		}
	}

	/**
	 * Segment an image based on color ranges.
	 * 
	 * @param input
	 *            The image on which to perform the RGB threshold.
	 * @param red
	 *            The min and max red.
	 * @param green
	 *            The min and max green.
	 * @param blue
	 *            The min and max blue.
	 * @param output
	 *            The image in which to store the output.
	 */
	private void rgbThreshold(Mat input, double[] red, double[] green, double[] blue, Mat out) {
		Imgproc.cvtColor(input, out, Imgproc.COLOR_BGR2RGB);
		Core.inRange(out, new Scalar(red[0], green[0], blue[0]), new Scalar(red[1], green[1], blue[1]), out);
	}

	/**
	 * Sets the values of pixels in a binary image to their distance to the
	 * nearest black pixel.
	 * 
	 * @param input
	 *            The image on which to perform the Distance Transform.
	 * @param type
	 *            The Transform.
	 * @param maskSize
	 *            the size of the mask.
	 * @param output
	 *            The image in which to store the output.
	 */
	private void findContours(Mat input, boolean externalOnly, List<MatOfPoint> contours) {
		Mat hierarchy = new Mat();
		contours.clear();
		int mode;
		if (externalOnly) {
			mode = Imgproc.RETR_EXTERNAL;
		} else {
			mode = Imgproc.RETR_LIST;
		}
		int method = Imgproc.CHAIN_APPROX_SIMPLE;
		Imgproc.findContours(input, contours, hierarchy, mode, method);
	}

	/**
	 * Compute the convex hulls of contours.
	 * 
	 * @param inputContours
	 *            The contours on which to perform the operation.
	 * @param outputContours
	 *            The contours where the output will be stored.
	 */
	private void convexHulls(List<MatOfPoint> inputContours, ArrayList<MatOfPoint> outputContours) {
		final MatOfInt hull = new MatOfInt();
		outputContours.clear();
		for (int i = 0; i < inputContours.size(); i++) {
			final MatOfPoint contour = inputContours.get(i);
			final MatOfPoint mopHull = new MatOfPoint();
			Imgproc.convexHull(contour, hull);
			mopHull.create((int) hull.size().height, 1, CvType.CV_32SC2);
			for (int j = 0; j < hull.size().height; j++) {
				int index = (int) hull.get(j, 0)[0];
				double[] point = new double[] { contour.get(index, 0)[0], contour.get(index, 0)[1] };
				mopHull.put(j, 0, point);
			}
			outputContours.add(mopHull);
		}
	}

	/**
	 * Filters out contours that do not meet certain criteria.
	 * 
	 * @param inputContours
	 *            is the input list of contours
	 * @param output
	 *            is the the output list of contours
	 * @param minArea
	 *            is the minimum area of a contour that will be kept
	 * @param minPerimeter
	 *            is the minimum perimeter of a contour that will be kept
	 * @param minWidth
	 *            minimum width of a contour
	 * @param maxWidth
	 *            maximum width
	 * @param minHeight
	 *            minimum height
	 * @param maxHeight
	 *            maximimum height
	 * @param Solidity
	 *            the minimum and maximum solidity of a contour
	 * @param minVertexCount
	 *            minimum vertex Count of the contours
	 * @param maxVertexCount
	 *            maximum vertex Count
	 * @param minRatio
	 *            minimum ratio of width to height
	 * @param maxRatio
	 *            maximum ratio of width to height
	 */
	private void filterContours(List<MatOfPoint> inputContours, double minArea, double minPerimeter, double minWidth,
			double maxWidth, double minHeight, double maxHeight, double[] solidity, double maxVertexCount,
			double minVertexCount, double minRatio, double maxRatio, List<MatOfPoint> output) {
		final MatOfInt hull = new MatOfInt();
		output.clear();
		// operation
		for (int i = 0; i < inputContours.size(); i++) {
			final MatOfPoint contour = inputContours.get(i);
			final Rect bb = Imgproc.boundingRect(contour);
			if (bb.width < minWidth || bb.width > maxWidth)
				continue;
			if (bb.height < minHeight || bb.height > maxHeight)
				continue;
			final double area = Imgproc.contourArea(contour);
			if (area < minArea)
				continue;
			if (Imgproc.arcLength(new MatOfPoint2f(contour.toArray()), true) < minPerimeter)
				continue;
			Imgproc.convexHull(contour, hull);
			MatOfPoint mopHull = new MatOfPoint();
			mopHull.create((int) hull.size().height, 1, CvType.CV_32SC2);
			for (int j = 0; j < hull.size().height; j++) {
				int index = (int) hull.get(j, 0)[0];
				double[] point = new double[] { contour.get(index, 0)[0], contour.get(index, 0)[1] };
				mopHull.put(j, 0, point);
			}
			final double solid = 100 * area / Imgproc.contourArea(mopHull);
			if (solid < solidity[0] || solid > solidity[1])
				continue;
			if (contour.rows() < minVertexCount || contour.rows() > maxVertexCount)
				continue;
			final double ratio = bb.width / (double) bb.height;
			if (ratio < minRatio || ratio > maxRatio)
				continue;
			output.add(contour);
		}
	}

}
